### ISSUE TITLE
Utf8Error in src\lib.rs:38:20

### ISSUE THREAD

**Issue by Sergej-Popov** [divy-work/deno-notify#1]
Hi, trying to use the module but getting rust errors.

OS: win 10
`deno --version`
```
deno 1.6.1 (release, x86_64-pc-windows-msvc)
v8 8.8.278.2
typescript 4.1.2
```

`.\test.ts`
```ts
import Notify from "https://raw.githubusercontent.com/littledivy/deno-notify/master/mod.ts";
Notify("Hello", "World!");
```

`deno run -A -r --unstable .\test.ts`
```
INFO load deno plugin "autopilot_deno" from local "C:\dev\do\.deno_plugins\autopilot_deno_bc782ffe4afd8b962e0e19a24ad8864f.dll"
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0, error_len: Some(1) }', src\lib.rs:38:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

With `RUST_BACKTRACE=full`:

<details><summary>EXPAND</summary>
<p>

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', src\lib.rs:39:32
stack backtrace:
   0:     0x7ffdfdcbb51f - CrashForExceptionInNonABICompliantCodeRange
   1:     0x7ffdfdccd3db - rust_eh_personality
   2:     0x7ffdfdcb9c0c - CrashForExceptionInNonABICompliantCodeRange
   3:     0x7ffdfdcbe18c - CrashForExceptionInNonABICompliantCodeRange
   4:     0x7ffdfdcbdddf - CrashForExceptionInNonABICompliantCodeRange
   5:     0x7ffdfdcbe837 - CrashForExceptionInNonABICompliantCodeRange
   6:     0x7ffdfdcbe3bf - CrashForExceptionInNonABICompliantCodeRange
   7:     0x7ffdfdccbce0 - rust_eh_personality
   8:     0x7ffdfdccbb03 - rust_eh_personality
   9:     0x7ffdfdb42d18 - <unknown>
  10:     0x7ffdfdb4b0ae - deno_plugin_init
  11:     0x7ff7fa118070 - <unknown>
  12:     0x7ff7fa0ceef8 - <unknown>
  13:     0x7ff7fa117cbb - <unknown>
  14:     0x7ff7fa0ceef8 - <unknown>
  15:     0x7ff7f9f093f8 - <unknown>
  16:     0x7ff7fa86d40b - CrashForExceptionInNonABICompliantCodeRange
  17:     0x7ff7fa86c833 - CrashForExceptionInNonABICompliantCodeRange
  18:     0x7ff7fa86bd5b - CrashForExceptionInNonABICompliantCodeRange
  19:     0x7ff7fa86b997 - CrashForExceptionInNonABICompliantCodeRange
  20:     0x7ff7fa90f95c - CrashForExceptionInNonABICompliantCodeRange
  21:     0x7ff7fa8a902f - CrashForExceptionInNonABICompliantCodeRange
  22:     0x7ff7fa8a902f - CrashForExceptionInNonABICompliantCodeRange
  23:     0x7ff7fa8a902f - CrashForExceptionInNonABICompliantCodeRange
  24:     0x7ff7fa8d8611 - CrashForExceptionInNonABICompliantCodeRange
  25:     0x7ff7fa8a6c7b - CrashForExceptionInNonABICompliantCodeRange
  26:     0x7ff7fa8a68cc - CrashForExceptionInNonABICompliantCodeRange
  27:     0x7ff7fa6e2a68 - <unknown>
  28:     0x7ff7fa6e30bc - <unknown>
  29:     0x7ff7fa6e302e - <unknown>
  30:     0x7ff7fa6eb27f - <unknown>
  31:     0x7ff7fa6eac83 - <unknown>
  32:     0x7ff7fa6eac96 - <unknown>
  33:     0x7ff7fab699e1 - CrashForExceptionInNonABICompliantCodeRange
  34:     0x7ff7fa90f95c - CrashForExceptionInNonABICompliantCodeRange
  35:     0x7ff7fa959d5b - CrashForExceptionInNonABICompliantCodeRange
  36:     0x7ff7fa8c95ae - CrashForExceptionInNonABICompliantCodeRange
  37:     0x7ff7fa8a6b8c - CrashForExceptionInNonABICompliantCodeRange
  38:     0x7ff7fa6e29bb - <unknown>
  39:     0x7ff7fa6e30bc - <unknown>
  40:     0x7ff7fa6e31bf - <unknown>
  41:     0x7ff7fa79dfb8 - CrashForExceptionInNonABICompliantCodeRange
  42:     0x7ff7fa79dd95 - CrashForExceptionInNonABICompliantCodeRange
  43:     0x7ff7fa67db01 - <unknown>
  44:     0x7ff7fa601d62 - <unknown>
  45:     0x7ff7fa5f0ea5 - <unknown>
  46:     0x7ff7fa3c1f8a - <unknown>
  47:     0x7ff7f9f1f703 - <unknown>
  48:     0x7ff7fa085a28 - <unknown>
  49:     0x7ff7f9db26b5 - <unknown>
  50:     0x7ff7f9da1c91 - <unknown>
  51:     0x7ff7fa08139a - <unknown>
  52:     0x7ff7f9e9b24a - <unknown>
  53:     0x7ff7f9cfaf30 - <unknown>
  54:     0x7ff7f9ea57fb - <unknown>
  55:     0x7ff7fb0ad920 - CrashForExceptionInNonABICompliantCodeRange
  56:     0x7ffe5dd26fd4 - BaseThreadInitThunk
  57:     0x7ffe5e65cec1 - RtlUserThreadStart
```
</p>
</details>

Am I using it wrong? Any help appreciated.

**Comment by Sergej-Popov** [comment]
Similar results on Ubuntu 20.04.1 LTS
```
INFO downloading deno plugin "autopilot_deno" from "https://github.com/divy-work/deno-notify/releases/latest/download/libdeno_notify.so"
INFO load deno plugin "autopilot_deno" from local "~/bin/.deno_plugins/autopilot_deno_a18e53dd45382429e23ae8884d249d18.so"
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0, error_len: None }', src/lib.rs:38:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```
